---
title: "RWorksheet_Cacho#4a"
author: "Janelle Cacho"
date: "2024-10-14"
output: pdf_document
---


```{r}
# 1
shoesize1 <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5)
height1 <- c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.0, 67.0, 71.0, 71.0)
gender1 <- c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", "M", "F", "M", "M")

shoesize2 <- c(13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0)
height2 <- c(77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0)
gender2 <- c("M", "M", "F", "F", "M", "F", "F", "M", "M", "F", "M", "M", "M", "M")

df <- data.frame(
  ShoeSize = c(shoesize1, shoesize2),
  Height = c(height1, height2),
  Gender = c(gender1, gender2)
)
df

write.csv(df, "sample_data.csv", row.names = FALSE)
# 1b
male_data <- subset(df, Gender == "M")
female_data <- subset(df, Gender== "F")

male_data
female_data

# 1c
mean_shoesize <- mean(df$ShoeSize)
mean_height <- mean(df$Height)

mean_shoesize 
mean_height

# 1d
correlation <- cor(df$ShoeSize, df$Height, use = "complete.obs")
print(paste("Correlation between Shoe Size and Height:", correlation))
```

```{r}
# 2
monthsvec <- c("March","April","January","November","January",
"September","October","September","November","August", "January","November","November","February","May","August",
"July","December","August","August","September","November","February", "April")

factor_monthsvec <- factor(monthsvec)

factor_monthsvec

levels(factor_monthsvec)


# 3
summary(monthsvec)

summary(factor_monthsvec)

# 4
direction <- c("East", "West", "North")
frequency <- c(1,4,3)
factor_data <- factor(direction, levels = c("East", "West", "North"))

factor_data

new_order_data <- factor(factor_data, levels = c("East", "West", "North"))

new_order_data
```
```{r}
# 5
write.csv("import_march.csv", row.names = FALSE)
data <- read.table("import_march.csv", header = TRUE, sep = ",")
View(data)
```

```{r}
# 6
number <- 40
if (!is.na(number) && (number < 1 || number > 50)) {
  stop("The number selected is beyond the range of 1 to 50.")
} else if (number == 20){
  print("TRUE")
  } else {
  print(paste("The number is:", number))
}
```

```{r}
# 7
min_bills <- function(price){
  bills <- c(50, 100, 200, 500, 1000)
  count <- 0
  for (bill in bills){
    count <- count + price %/% bill
    price <- price %% bill
  }
  return(count)
}

snackPrice <- as.integer(readline(prompt = "Enter the price of the snack:"))
print(paste("Minimum  number of bills needed: ", min_bills(snackPrice)))
```

```{r}
# 8a
grades <- data.frame (
          Name = c("Annie", "Thea", "Steve", "Hanna"),
          Grade1 = c(85, 65, 75, 95),
          Grade2 = c(65, 75, 55, 75), 
          Grade3 = c(85, 90, 80, 100),
          Grade4 = c(100, 90, 85, 90)
)
grades

for (i in 1:nrow(grades)) {
  highest <- grades[i, 2]
  for (j in 3:5) {
    if (grades[i, j] > highest) {
      highest <- grades[i, j]
    }
  }
  if (highest > 90) {
    cat(grades$Name[i], "'s highest grade this semester is", highest, "\n")
  }
}
```



